//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.DTW.Win.Constans.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.DTW.Win.Constans.Idioma.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente de importación de datos.
        /// </summary>
        internal static string Label00001 {
            get {
                return ResourceManager.GetString("Label00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a este asistente lo guía a través de los pasos para importar datos..
        /// </summary>
        internal static string Label00002 {
            get {
                return ResourceManager.GetString("Label00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente de importación de datos para SAP Business One..
        /// </summary>
        internal static string Label00003 {
            get {
                return ResourceManager.GetString("Label00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este asistente lo ayuda a importar datos de un sistema heredado de información SAP Business One..
        /// </summary>
        internal static string Label00004 {
            get {
                return ResourceManager.GetString("Label00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antes de continuar, asegúrese de tener los archivos de datos de origen disponibles como.
        /// </summary>
        internal static string Label00005 {
            get {
                return ResourceManager.GetString("Label00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a un archivo plano o en una base de datos a la que se puede acceder a través de ODBC.
        /// </summary>
        internal static string Label00006 {
            get {
                return ResourceManager.GetString("Label00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para comenzar, elija el botón &quot;Siguiente&quot;.
        /// </summary>
        internal static string Label00007 {
            get {
                return ResourceManager.GetString("Label00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1 : seleccione el tipo de datos.
        /// </summary>
        internal static string Label00008 {
            get {
                return ResourceManager.GetString("Label00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tipo de datos que desea importar. Para continuar, elija el botón &quot;Siguiente&quot;.
        /// </summary>
        internal static string Label00009 {
            get {
                return ResourceManager.GetString("Label00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de configuración (por ejemplo, códigos de impuestos, banco, etc.).
        /// </summary>
        internal static string Label00010 {
            get {
                return ResourceManager.GetString("Label00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Data (for example, Business Partners, and so on).
        /// </summary>
        internal static string Label00011 {
            get {
                return ResourceManager.GetString("Label00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos transaccionales (por ejemplo, facturas de venta, órdenes de compra, etc.).
        /// </summary>
        internal static string Label00012 {
            get {
                return ResourceManager.GetString("Label00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2: especificar el tipo de operación.
        /// </summary>
        internal static string Label00013 {
            get {
                return ResourceManager.GetString("Label00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tipo de operación que desea realizar al importar los datos..
        /// </summary>
        internal static string Label00014 {
            get {
                return ResourceManager.GetString("Label00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para continuar, seleccione el botón &quot;Siguiente&quot;..
        /// </summary>
        internal static string Label00015 {
            get {
                return ResourceManager.GetString("Label00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevos datos.
        /// </summary>
        internal static string Label00016 {
            get {
                return ResourceManager.GetString("Label00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar datos existentes.
        /// </summary>
        internal static string Label00017 {
            get {
                return ResourceManager.GetString("Label00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevos datos y actualizar datos existentes.
        /// </summary>
        internal static string Label00018 {
            get {
                return ResourceManager.GetString("Label00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3: seleccione un objeto comercial.
        /// </summary>
        internal static string Label00019 {
            get {
                return ResourceManager.GetString("Label00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3: seleccione un objeto comercial.
        /// </summary>
        internal static string Label00020 {
            get {
                return ResourceManager.GetString("Label00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objecto Seleccionado.
        /// </summary>
        internal static string Label00021 {
            get {
                return ResourceManager.GetString("Label00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt; Atrás.
        /// </summary>
        internal static string LabelAntes {
            get {
                return ResourceManager.GetString("LabelAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string LabelAyuda {
            get {
                return ResourceManager.GetString("LabelAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string LabelCancelar {
            get {
                return ResourceManager.GetString("LabelCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string LabelCargar {
            get {
                return ResourceManager.GetString("LabelCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Plantilla.
        /// </summary>
        internal static string LabelDescargar {
            get {
                return ResourceManager.GetString("LabelDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string LabelFinalizar {
            get {
                return ResourceManager.GetString("LabelFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente &gt;.
        /// </summary>
        internal static string LabelSiguiente {
            get {
                return ResourceManager.GetString("LabelSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3: seleccione un objeto comercial.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAP Business One Data Transfer Workbench.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objecto.
        /// </summary>
        internal static string TituloTablaDTW {
            get {
                return ResourceManager.GetString("TituloTablaDTW", resourceCulture);
            }
        }
    }
}
